export const CHNAGE_ACTION_STATUS = 'CHNAGE_ACTION_STATUS';
export const TEST_REQUEST = 'TEST_REQUEST';
export const TEST_REQUEST_SUCCESS = 'TEST_REQUEST_SUCCESS';
export const TEST_REQUEST_FAILED = 'TEST_REQUEST_FAILED';

export const ADD_TRANSACTION_REQUEST = 'ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_REQUEST_SUCCESS =
  'ADD_TRANSACTION_REQUEST_SUCCESS';
export const ADD_TRANSACTION_REQUEST_FAILED = 'ADD_TRANSACTION_REQUEST_FAILED';

export const GET_TRANSACTION_REQUEST = 'GET_TRANSACTION_REQUEST';
export const GET_TRANSACTION_REQUEST_SUCCESS =
  'GET_TRANSACTION_REQUEST_SUCCESS';
export const GET_TRANSACTION_REQUEST_FAILED = 'GET_TRANSACTION_REQUEST_FAILED';
