export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_REQUEST_SUCCESS = 'CREATE_ACCOUNT_REQUEST_SUCCESS';
export const CREATE_ACCOUNT_REQUEST_FAILED = 'CREATE_ACCOUNT_REQUEST_FAILED';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_REQUEST_SUCCESS = 'GET_ACCOUNT_REQUEST_SUCCESS';
export const GET_ACCOUNT_REQUEST_FAILED = 'GET_ACCOUNT_REQUEST_FAILED';
